
import { GenerationKey } from './types';

export const GENERATION_RANGES: Record<GenerationKey, { start: number; end: number; name: string }> = {
  kanto: { start: 1, end: 151, name: 'Kanto' },
  johto: { start: 152, end: 251, name: 'Johto' },
  hoenn: { start: 252, end: 386, name: 'Hoenn' },
  sinnoh: { start: 387, end: 493, name: 'Sinnoh' },
  unova: { start: 494, end: 649, name: 'Unova' },
  kalos: { start: 650, end: 721, name: 'Kalos' },
  alola: { start: 722, end: 809, name: 'Alola' },
  galar: { start: 810, end: 898, name: 'Galar' },
  paldea: { start: 906, end: 1025, name: 'Paldea' },
};

export const GENERATION_ROMAN_NUMERALS: Record<string, GenerationKey> = {
  'i': 'kanto',
  'ii': 'johto',
  'iii': 'hoenn',
  'iv': 'sinnoh',
  'v': 'unova',
  'vi': 'kalos',
  'vii': 'alola',
  'viii': 'galar',
  'ix': 'paldea',
};

export const TYPE_COLORS: Record<string, string> = {
  normal: '#A8A77A',
  fire: '#EE8130',
  water: '#6390F0',
  electric: '#F7D02C',
  grass: '#7AC74C',
  ice: '#96D9D6',
  fighting: '#C22E28',
  poison: '#A33EA1',
  ground: '#E2BF65',
  flying: '#A98FF3',
  psychic: '#F95587',
  bug: '#A6B91A',
  rock: '#B6A136',
  ghost: '#735797',
  dragon: '#6F35FC',
  dark: '#705746',
  steel: '#B7B7CE',
  fairy: '#D685AD',
};

export const TYPE_EFFECTIVENESS: Record<string, Record<string, number>> = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water: { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass: { fire: 0.5, water: 2, grass: 0.5, poison: 0.5, ground: 2, flying: 0.5, bug: 0.5, rock: 2, dragon: 0.5, steel: 0.5 },
  ice: { fire: 0.5, water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: { normal: 2, ice: 2, poison: 0.5, flying: 0.5, psychic: 0.5, bug: 0.5, rock: 2, ghost: 0, dark: 2, steel: 2, fairy: 0.5 },
  poison: { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground: { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying: { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic: { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug: { fire: 0.5, grass: 2, fighting: 0.5, poison: 0.5, flying: 0.5, psychic: 2, ghost: 0.5, dark: 2, steel: 0.5, fairy: 0.5 },
  rock: { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost: { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon: { dragon: 2, steel: 0.5, fairy: 0 },
  dark: { fighting: 0.5, psychic: 2, ghost: 2, dark: 0.5, fairy: 0.5 },
  steel: { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, steel: 0.5, fairy: 2 },
  fairy: { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 },
};

export const NATURES = [
    { name: 'Hardy', increased_stat: null, decreased_stat: null },
    { name: 'Lonely', increased_stat: 'attack', decreased_stat: 'defense' },
    { name: 'Brave', increased_stat: 'attack', decreased_stat: 'speed' },
    { name: 'Adamant', increased_stat: 'attack', decreased_stat: 'sp_atk' },
    { name: 'Naughty', increased_stat: 'attack', decreased_stat: 'sp_def' },
    { name: 'Bold', increased_stat: 'defense', decreased_stat: 'attack' },
    { name: 'Docile', increased_stat: null, decreased_stat: null },
    { name: 'Relaxed', increased_stat: 'defense', decreased_stat: 'speed' },
    { name: 'Impish', increased_stat: 'defense', decreased_stat: 'sp_atk' },
    { name: 'Lax', increased_stat: 'defense', decreased_stat: 'sp_def' },
    { name: 'Timid', increased_stat: 'speed', decreased_stat: 'attack' },
    { name: 'Hasty', increased_stat: 'speed', decreased_stat: 'defense' },
    { name: 'Serious', increased_stat: null, decreased_stat: null },
    { name: 'Jolly', increased_stat: 'speed', decreased_stat: 'sp_atk' },
    { name: 'Naive', increased_stat: 'speed', decreased_stat: 'sp_def' },
    { name: 'Modest', increased_stat: 'sp_atk', decreased_stat: 'attack' },
    { name: 'Mild', increased_stat: 'sp_atk', decreased_stat: 'defense' },
    { name: 'Quiet', increased_stat: 'sp_atk', decreased_stat: 'speed' },
    { name: 'Bashful', increased_stat: null, decreased_stat: null },
    { name: 'Rash', increased_stat: 'sp_atk', decreased_stat: 'sp_def' },
    { name: 'Calm', increased_stat: 'sp_def', decreased_stat: 'attack' },
    { name: 'Gentle', increased_stat: 'sp_def', decreased_stat: 'defense' },
    { name: 'Sassy', increased_stat: 'sp_def', decreased_stat: 'speed' },
    { name: 'Careful', increased_stat: 'sp_def', decreased_stat: 'sp_atk' },
    { name: 'Quirky', increased_stat: null, decreased_stat: null },
];